#!/bin/bash

#Install zsh
sudo yum install -y zsh
chsh -s $(which zsh)

# Install python3, pip, and venv
sudo yum install -y python3
sudo yum install -y python3-pip
sudo yum install -y python3.8-venv

# Install tmux
sudo yum install -y tmux
